include("/home/runner/work/FastNoise2/FastNoise2/cmake/CPM.cmake")
CPMAddPackage("NAME;corrade;GITHUB_REPOSITORY;mosra/corrade;GIT_TAG;f37591439479a5169134f8f2eba551b95054057a;GIT_SUBMODULES;src;EXCLUDE_FROM_ALL;YES;OPTIONS;CORRADE_BUILD_STATIC ON;CORRADE_BUILD_STATIC_UNIQUE_GLOBALS OFF;CORRADE_MSVC_COMPATIBILITY ON;CORRADE_WITH_INTERCONNECT OFF;CORRADE_WITH_TESTSUITE OFF")
set(corrade_FOUND TRUE)