hunter_config(magnum VERSION ${HUNTER_magnum_VERSION}
    CMAKE_ARGS 
	    BUILD_STATIC=ON
        BUILD_PLUGINS_STATIC=ON
		BUILD_SHARED_LIBS=OFF
        WITH_SDL2APPLICATION=ON
)

hunter_config(corrade VERSION ${HUNTER_corrade_VERSION}
    CMAKE_ARGS 
		BUILD_STATIC=ON
		BUILD_SHARED_LIBS=OFF
)