hunter_config(SDL2 VERSION ${HUNTER_SDL2_VERSION}
    CMAKE_ARGS 
		BUILD_SHARED_LIBS=OFF
)
hunter_config(magnum VERSION ${HUNTER_magnum_VERSION}
    CMAKE_ARGS 
	    BUILD_STATIC=ON
        BUILD_PLUGINS_STATIC=ON
		BUILD_SHARED_LIBS=OFF
        WITH_SDL2APPLICATION=ON
)

hunter_config(corrade VERSION ${HUNTER_corrade_VERSION}
    CMAKE_ARGS 
		BUILD_STATIC=ON
		BUILD_SHARED_LIBS=OFF
)

hunter_config(benchmark VERSION ${HUNTER_benchmark_VERSION}
    CMAKE_ARGS 
)