#pragma once

inline const char* gDemoNodeTrees[][2] =
{
    { "Simple Terrain", "EgACAAAAAAAgQBEAAAAAQBoAFADD9Sg/DQAEAAAAAAAgQAkAAAAAAD8BBAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNzEw+AJqZGT8=" },
    { "Cellular Caves", "FACamZk+GwABEgACAAAAAADgQBEAAACIQSAAFwABAAAACwADAAAAAgAAAAMAAAAEAAAAAAAAAD8BFQALAAMAAAACAAAAAwAAAAQAAAAAAAAAPwAAAAA/AAAAAD8AAAAAPwAAAAA/ARgAAACAvwAAgD89ChdAUrgeQBQAAACgQAYAAI/C9TwACtcjPgDhehQ/" },
};
