#pragma once

inline const char* gDemoNodeTrees[][2] =
{
    { "Simple Terrain", "EgACAAAAAAAgQBEAAAAAQBoAFADD9Sg/DQAEAAAAAAAgQAkAAAAAAD8BBAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNzEw+AJqZGT8=" },
    { "Cellular Caves", "FACamZk+GwABEgACAAAAAADgQBEAAACIQSAAFwABAAAACwADAAAAAgAAAAMAAAAEAAAAAAAAAD8BFQD//wAAAAAAAD8AAAAAPwAAAAA/AAAAAD8BGAAAAIC/AACAPz0KF0BSuB5AFAAAAKBABgAAj8L1PAAK1yM+AOF6FD8=" },
};
